import {
  UserProfile,
  LeaveOrWfhRequest,
  TeamMemberStatus,
  NotificationItem,
  PolicyFaqItem,
  BiometricDeviceConfig,
  AttendanceRecord,
  SalaryDeduction,
  SalaryAdvance,
} from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'emp-1',
    name: 'سارة المنصور',
    nameEn: 'Sara Al-Mansoor',
    email: 'sara.mansoor@dawamy.app',
    role: 'employee',
    title: 'مهندسة برمجيات أولى (Senior Software Engineer)',
    titleEn: 'Senior Software Engineer',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    managerName: 'م. طارق الخالدي',
    biometricEnrollId: '101',
    salary: 18500,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="280" height="90" viewBox="0 0 280 90"><path d="M 25 55 Q 60 15, 85 50 T 140 45 T 195 40 Q 220 75, 245 25" fill="none" stroke="%231E3A8A" stroke-width="3" stroke-linecap="round"/><path d="M 45 72 Q 130 65, 215 74" fill="none" stroke="%231E3A8A" stroke-width="2" stroke-linecap="round"/></svg>',
    signatureType: 'drawn',
    signatureJobTitle: 'مهندسة برمجيات أولى',
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 3,
      annualLeaveTotal: 25,
      annualLeaveUsed: 6,
      sickLeaveUsed: 1,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'wfh_active',
    checkInTime: '08:45 AM',
    currentTasks: [
      'تطوير نظام الاعتمادات الفورية وتحديث API الخادم',
      'مراجعة كود البنية التحتية لحاويات Cloud Run',
      'اجتماع المواءمة التقنية وتنسيق المهام',
    ],
    dailyTasks: [
      {
        id: 'task-101',
        title: 'تطوير نظام الاعتمادات الفورية وتحديث API الخادم',
        dueTime: '11:30 AM',
        completed: true,
        priority: 'high',
        category: 'برمجة وتطوير',
        notes: 'تم فحص الـ Endpoints وتكامل Firestore بنجاح',
        completedAt: '10:45 AM',
      },
      {
        id: 'task-102',
        title: 'مراجعة كود البنية التحتية لحاويات Cloud Run والمنفذ 3000',
        dueTime: '02:00 PM',
        completed: false,
        priority: 'high',
        category: 'بنية تحتية',
        notes: 'التحقق من إعدادات Nginx والتأكد من استقرار المزامنة',
      },
      {
        id: 'task-103',
        title: 'اجتماع المواءمة التقنية ومزامنة الفريق الصباحي',
        dueTime: '03:30 PM',
        completed: false,
        priority: 'medium',
        category: 'اجتماعات',
        notes: 'استعراض مخرجات العمل عن بُعد مع المهندس طارق',
      },
      {
        id: 'task-104',
        title: 'إرسال تقرير الإنجاز اليومي (Daily Standup Recap) في سلاك',
        dueTime: '05:00 PM',
        completed: false,
        priority: 'normal',
        category: 'تقارير ومتابعة',
        notes: 'مشاركة ملخص المهام المنجزة قبل نهاية الدوام',
      },
    ],
  },
  {
    id: 'emp-2',
    name: 'طارق الخالدي',
    nameEn: 'Tariq Al-Khalidi',
    email: 'tariq.khalidi@dawamy.app',
    role: 'manager',
    title: 'مدير الفريق الهندسي (Engineering Lead)',
    titleEn: 'Engineering Lead',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    managerName: 'د. خالد الزهراني',
    biometricEnrollId: '102',
    salary: 22000,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 2,
      annualLeaveTotal: 25,
      annualLeaveUsed: 4,
      sickLeaveUsed: 0,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'in_office',
    checkInTime: '08:15 AM',
    currentTasks: [
      'اجتماع مواءمة الربع السنوي مع الإدارة',
      'اعتماد طلبات الإجازات والعمل عن بعد للفريق',
      'مراجعة تقييم أداء مهندسي الفريق',
    ],
    dailyTasks: [
      {
        id: 'task-201',
        title: 'مراجعة واعتماد طلبات الإجازات والعمل عن بعد في المنصة',
        dueTime: '10:30 AM',
        completed: true,
        priority: 'high',
        category: 'اعتمادات وإشراف',
        completedAt: '09:50 AM',
      },
      {
        id: 'task-202',
        title: 'اجتماع مواءمة الربع السنوي مع الإدارة العامة',
        dueTime: '01:00 PM',
        completed: false,
        priority: 'high',
        category: 'اجتماعات',
      },
      {
        id: 'task-203',
        title: 'مراجعة الخطة التشغيلية لمهندسي البرمجيات لشهر سبتمبر',
        dueTime: '04:30 PM',
        completed: false,
        priority: 'medium',
        category: 'تخطيط واستراتيجية',
      },
    ],
  },
  {
    id: 'emp-3',
    name: 'ريم العتيبي',
    nameEn: 'Reem Al-Otaibi',
    email: 'reem.otaibi@dawamy.app',
    role: 'hr',
    title: 'أخصائية الموارد البشرية والامتثال (HR & People Specialist)',
    titleEn: 'HR & People Specialist',
    department: 'الموارد البشرية (People & HR)',
    departmentEn: 'Human Resources',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    managerName: 'أ. عبد الله السالم',
    biometricEnrollId: '103',
    salary: 16000,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 1,
      annualLeaveTotal: 25,
      annualLeaveUsed: 2,
      sickLeaveUsed: 0,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'in_office',
    checkInTime: '08:00 AM',
    currentTasks: [
      'تدقيق سجلات الحضور وساعات الدوام المرن',
      'تحديث سياسات العمل الهجين والامتثال للائحة',
      'مراجعة خطط الإنابة وتغطية الإجازات السنوية',
    ],
    dailyTasks: [
      {
        id: 'task-301',
        title: 'تدقيق سجلات الحضور الافتراضي وساعات الدوام المرن',
        dueTime: '11:00 AM',
        completed: true,
        priority: 'high',
        category: 'موارد بشرية وامتثال',
        completedAt: '10:15 AM',
      },
      {
        id: 'task-302',
        title: 'تحديث دليل سياسات العمل الهجين ولائحة نظام العمل',
        dueTime: '02:30 PM',
        completed: false,
        priority: 'medium',
        category: 'سياسات ولوائح',
      },
      {
        id: 'task-303',
        title: 'مراجعة وتأكيد خطط الإنابة للموظفين المسافرين هذا الأسبوع',
        dueTime: '04:00 PM',
        completed: false,
        priority: 'normal',
        category: 'متابعة وإشراف',
      },
    ],
  },
  {
    id: 'emp-4',
    name: 'أحمد القحطاني',
    nameEn: 'Ahmed Al-Qahtani',
    email: 'ahmed.qahtani@dawamy.app',
    role: 'employee',
    title: 'مطور واجهات أمامية (Frontend Engineer)',
    titleEn: 'Frontend Engineer',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    managerName: 'م. طارق الخالدي',
    biometricEnrollId: '104',
    salary: 14500,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 4,
      annualLeaveTotal: 25,
      annualLeaveUsed: 7,
      sickLeaveUsed: 2,
      emergencyLeaveUsed: 1,
    },
    todayStatus: 'in_office',
    checkInTime: '08:30 AM',
    currentTasks: ['تطوير الواجهات التفاعلية', 'تحسين سرعة العرض'],
  },
  {
    id: 'emp-5',
    name: 'نورة الدوسري',
    nameEn: 'Noura Al-Dossari',
    email: 'noura.dossari@dawamy.app',
    role: 'employee',
    title: 'مصممة تجربة المستخدم (UI/UX Designer)',
    titleEn: 'UI/UX Designer',
    department: 'المنتج والتصميم (Product & Design)',
    departmentEn: 'Product & Design',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    managerName: 'م. طارق الخالدي',
    biometricEnrollId: '105',
    salary: 13800,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 2,
      annualLeaveTotal: 25,
      annualLeaveUsed: 5,
      sickLeaveUsed: 0,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'deep_focus',
    checkInTime: '09:00 AM',
    currentTasks: ['تصميم شاشات نظام البصمة', 'إعداد دليل الألوان المعتمد'],
  },
  {
    id: 'emp-6',
    name: 'فيصل الغامدي',
    nameEn: 'Faisal Al-Ghamdi',
    email: 'faisal.ghamdi@dawamy.app',
    role: 'employee',
    title: 'مهندس DevOps وسيرفرات (DevOps Engineer)',
    titleEn: 'DevOps Engineer',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    managerName: 'م. طارق الخالدي',
    biometricEnrollId: '106',
    salary: 15200,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 5,
      annualLeaveTotal: 25,
      annualLeaveUsed: 8,
      sickLeaveUsed: 1,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'in_office',
    checkInTime: '08:10 AM',
    currentTasks: ['مراقبة اتصال أجهزة البصمة', 'أمان الـ Webhook'],
  },
  {
    id: 'emp-7',
    name: 'ياسمين الحربي',
    nameEn: 'Yasmin Al-Harbi',
    email: 'yasmin.harbi@dawamy.app',
    role: 'employee',
    title: 'محللة نظم وضمان الجودة (QA Specialist)',
    titleEn: 'QA Specialist',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    managerName: 'م. طارق الخالدي',
    biometricEnrollId: '107',
    salary: 13000,
    salaryCurrency: 'ر.س',
    graceLateHoursMonthly: 4.0,
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 3,
      annualLeaveTotal: 25,
      annualLeaveUsed: 3,
      sickLeaveUsed: 0,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'in_meeting',
    checkInTime: '08:25 AM',
    currentTasks: ['اختبارات التكامل الشاملة', 'فحص شيت الإكسيل'],
  },
];

export const INITIAL_REQUESTS: LeaveOrWfhRequest[] = [
  {
    id: 'REQ-1088',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userTitle: 'مطور واجهات أمامية (Frontend Engineer)',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    type: 'annual_leave',
    startDate: '2026-09-01',
    endDate: '2026-09-08',
    totalDays: 6,
    reason: 'إجازة سنوية للاستجمام والسفر العائلي مجدولة مسبقاً بموافقة الإدارة.',
    isAiGeneratedReason: false,
    handoverColleague: 'سارة المنصور',
    handoverPlan: 'تسليم كافة أكواد الواجهات ومتابعة الصيانة مع سارة.',
    status: 'approved',
    createdAt: '2026-08-25T08:00:00Z',
    managerNotes: 'معتمد مع تمنياتنا بإجازة سعيدة.',
    approvedByManagerAt: '2026-08-25T09:30:00Z',
  },
  {
    id: 'REQ-1092',
    userId: 'emp-1',
    userName: 'سارة المنصور',
    userTitle: 'مهندسة برمجيات أولى',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    type: 'remote',
    startDate: '2026-09-03',
    endDate: '2026-09-03',
    totalDays: 1,
    reason: 'التركيز المكثف على إنهاء اختبارات الأداء وسد الثغرات الأمنية قبل إطلاق الإصدار القادم.',
    isAiGeneratedReason: true,
    handoverColleague: 'أحمد القحطاني',
    handoverPlan: 'متابعة التنبيهات العاجلة على سيرفر الإنتاج في حال دعت الحاجة.',
    status: 'approved',
    createdAt: '2026-09-01T10:30:00Z',
    managerNotes: 'معتمد مع تمنياتي بالتوفيق في إنجاز الاختبارات.',
    approvedByManagerAt: '2026-09-01T11:00:00Z',
  },
  {
    id: 'REQ-1093',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userTitle: 'مطور واجهات أمامية (Frontend Engineer)',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    type: 'annual_leave',
    startDate: '2026-09-10',
    endDate: '2026-09-14',
    totalDays: 3,
    reason: 'إجازة سنوية مجدولة للراحة وتجديد الطاقة بعد انتهاء مرحلة التصميم الرئيسية.',
    isAiGeneratedReason: true,
    handoverColleague: 'سارة المنصور',
    handoverPlan: 'تم تسليم كافة ملفات Figma ومكونات React لسارة لتغطية أي تعديلات طارئة.',
    status: 'pending_manager',
    createdAt: '2026-09-02T08:15:00Z',
  },
  {
    id: 'REQ-1094',
    userId: 'emp-5',
    userName: 'نورة الدوسري',
    userTitle: 'مصممة تجربة المستخدم (UI/UX Designer)',
    department: 'التصميم والابتكار',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    type: 'remote',
    startDate: '2026-09-04',
    endDate: '2026-09-04',
    totalDays: 1,
    reason: 'إجراء مقابلات بحثية مع المستخدمين واختبار النماذج الأولية في بيئة هادئة.',
    isAiGeneratedReason: true,
    handoverColleague: 'سارة المنصور',
    status: 'pending_manager',
    createdAt: '2026-09-02T09:40:00Z',
  },
  {
    id: 'REQ-1090',
    userId: 'emp-6',
    userName: 'فيصل الغامدي',
    userTitle: 'أخصائي قواعد بيانات (DevOps & DBA)',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    type: 'sick_leave',
    startDate: '2026-08-28',
    endDate: '2026-08-28',
    totalDays: 1,
    reason: 'مراجعة عيادة الأسنان وإجراء جراحة صغرى.',
    status: 'approved',
    createdAt: '2026-08-28T07:10:00Z',
    approvedByManagerAt: '2026-08-28T07:45:00Z',
    approvedByHrAt: '2026-08-28T08:30:00Z',
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMemberStatus[] = [
  {
    id: 'emp-1',
    name: 'سارة المنصور',
    nameEn: 'Sara Al-Mansoor',
    role: 'مهندسة برمجيات أولى',
    roleEn: 'Senior Software Engineer',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'wfh_active',
    location: 'الرياض (عن بُعد)',
    locationEn: 'Riyadh (Remote)',
    checkInTime: '08:45 AM',
    currentFocus: 'تطوير وحدة الدوام المرن والذكاء الاصطناعي',
    currentFocusEn: 'Developing smart hybrid workflow & Gemini AI logic',
  },
  {
    id: 'emp-2',
    name: 'طارق الخالدي',
    nameEn: 'Tariq Al-Khalidi',
    role: 'مدير الفريق الهندسي',
    roleEn: 'Engineering Lead',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'in_office',
    location: 'المكتب الرئيسي - الدور 4',
    locationEn: 'HQ - 4th Floor',
    checkInTime: '08:15 AM',
    currentFocus: 'مراجعات التصميم واعتماد الطلبات',
    currentFocusEn: 'Design review & approving pending team requests',
  },
  {
    id: 'emp-4',
    name: 'أحمد القحطاني',
    nameEn: 'Ahmed Al-Qahtani',
    role: 'مطور واجهات أمامية',
    roleEn: 'Frontend Engineer',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'in_office',
    location: 'المكتب الرئيسي - الدور 4',
    locationEn: 'HQ - 4th Floor',
    checkInTime: '08:30 AM',
    currentFocus: 'تحسين تجربة الجوال وتأثيرات الواجهة',
    currentFocusEn: 'Improving mobile responsiveness & UI micro-interactions',
  },
  {
    id: 'emp-5',
    name: 'نورة الدوسري',
    nameEn: 'Noura Al-Dossari',
    role: 'مصممة تجربة المستخدم',
    roleEn: 'UI/UX Designer',
    department: 'التصميم',
    departmentEn: 'Design & Innovation',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'deep_focus',
    location: 'المكتب الرئيسي - منطقة الهدوء',
    locationEn: 'HQ - Quiet Zone',
    checkInTime: '09:00 AM',
    currentFocus: 'تصميم نموذج تقويم الإجازات التفاعلي',
    currentFocusEn: 'Designing the interactive presence calendar mockup',
  },
  {
    id: 'emp-6',
    name: 'فيصل الغامدي',
    nameEn: 'Faisal Al-Ghamdi',
    role: 'مهندس DevOps وسيرفرات',
    roleEn: 'DevOps & DBA Specialist',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    status: 'in_office',
    location: 'المكتب الرئيسي - الدور 4',
    locationEn: 'HQ - 4th Floor',
    checkInTime: '08:10 AM',
    currentFocus: 'ضبط إعدادات Cloud Run ومراقبة المنفذ 3000',
    currentFocusEn: 'Monitoring Cloud Run container & port 3000 health',
  },
  {
    id: 'emp-7',
    name: 'ياسمين الحربي',
    nameEn: 'Yasmin Al-Harbi',
    role: 'محللة نظم وضمان الجودة',
    roleEn: 'QA & Systems Analyst',
    department: 'الجودة والأنظمة',
    departmentEn: 'QA & Quality Assurance',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'in_meeting',
    location: 'قاعة الاجتماعات 2B',
    locationEn: 'Meeting Room 2B',
    checkInTime: '08:50 AM',
    currentFocus: 'اختبار قبول المستخدم (UAT)',
    currentFocusEn: 'User Acceptance Testing (UAT)',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'تم اعتماد طلب العمل عن بعد ✅',
    titleEn: 'Remote Work Request Approved ✅',
    message: 'وافق المدير م. طارق الخالدي على طلبك للعمل عن بعد ليوم الخميس 3 سبتمبر.',
    messageEn: 'Engineering Lead Tariq Al-Khalidi approved your WFH request for Thu, Sep 3.',
    type: 'approval',
    timestamp: 'منذ 25 دقيقة',
    read: false,
    requestId: 'REQ-1092',
  },
  {
    id: 'notif-2',
    title: 'تذكير: تسجيل الحضور الافتراضي ⏰',
    titleEn: 'Virtual Check-In Logged ⏰',
    message: 'تم تسجيل حضورك الافتراضي بنجاح اليوم عند الساعة 08:45 ص.',
    messageEn: 'Your attendance check-in was successfully logged today at 08:45 AM.',
    type: 'system',
    timestamp: 'اليوم، 08:45 ص',
    read: true,
  },
  {
    id: 'notif-3',
    title: 'تحديث سياسة الدوام المرن 📢',
    titleEn: 'Hybrid Policy Update 📢',
    message: 'تم تحديث سياسة العمل الهجين مع إتاحة خيار العمل لنصف يوم مرن.',
    messageEn: 'Updated hybrid working guidelines with flexible half-day options.',
    type: 'reminder',
    timestamp: 'أمس، 02:00 م',
    read: true,
  },
];

export const POLICY_FAQS: PolicyFaqItem[] = [
  {
    questionAr: 'كم عدد أيام العمل عن بُعد المسموحة شهرياً؟',
    questionEn: 'How many WFH days are allowed per month?',
    summaryAr: 'يحق للموظف يومين في الأسبوع (بحد أقصى 8 أيام شهرياً) بموافقة المدير المباشر وتنسيق التغطية.',
    summaryEn: 'Up to 2 days per week (max 8 per month) with direct manager approval.',
    tag: 'العمل عن بعد (WFH)',
  },
  {
    questionAr: 'ما هي ساعات التواجد الأساسية (Core Hours) خلال العمل عن بعد؟',
    questionEn: 'What are the mandatory core hours during WFH?',
    summaryAr: 'ساعات التواجد الإلزامية عبر سلاك والبريد هي من 10:00 صباحاً وحتى 04:00 مساءً.',
    summaryEn: 'Core availability hours are 10:00 AM to 4:00 PM on Slack, Teams and email.',
    tag: 'ساعات الدوام',
  },
  {
    questionAr: 'ما هي المهلة الزمنية لتقديم طلب الإجازة السنوية؟',
    questionEn: 'What is the notice period for annual leave requests?',
    summaryAr: 'يجب تقديم طلب الإجازة السنوية قبل 48 ساعة على الأقل للإجازات القصيرة (1-3 أيام)، وقبل أسبوع للإجازات الأطول.',
    summaryEn: 'Submit at least 48 hours in advance for 1-3 days, and 1 week for longer leaves.',
    tag: 'الإجازات السنوية',
  },
  {
    questionAr: 'كيف يتم اعتماد الإجازة المرضية وتوثيقها؟',
    questionEn: 'How is sick leave verified and documented?',
    summaryAr: 'يجب رفع التقرير الطبي المعتمد من منصة صحتي أو المستشفى عبر المنصة خلال 24 ساعة من تاريخ الغياب.',
    summaryEn: 'Upload certified medical certificate via Sehaty/clinic within 24 hours.',
    tag: 'الإجازات المرضية',
  },
];

// ----------------------------------------------------
// INITIAL BIOMETRIC PUNCH DEVICES
// ----------------------------------------------------
export const INITIAL_BIOMETRIC_DEVICES: BiometricDeviceConfig[] = [
  {
    id: 'dev-1',
    name: 'جهاز البصمة - المدخل الرئيسي (HQ Main Gate)',
    ipAddress: '192.168.1.120',
    port: 4370,
    serialNumber: 'ZK-SB101-77829',
    protocol: 'adms',
    location: 'المبنى الرئيسي - بوابة الدخول 1',
    status: 'online',
    lastSyncTime: '2026-09-03T08:50:00Z',
    totalRegisteredUsers: 154,
    apiKey: 'zk_live_token_77829',
    firmwareVersion: 'Ver 6.60 (Apr 2026)',
  },
  {
    id: 'dev-2',
    name: 'جهاز بصمة الوجه - الدور الرابع (Engineering Floor)',
    ipAddress: '192.168.1.125',
    port: 8080,
    serialNumber: 'HIK-FC671-99210',
    protocol: 'rest_webhook',
    location: 'برج الابتكار - الطابق 4 (قطاع الهندسة)',
    status: 'online',
    lastSyncTime: '2026-09-03T08:52:00Z',
    totalRegisteredUsers: 48,
    apiKey: 'hik_face_live_99210',
    firmwareVersion: 'v3.2.14_build2603',
  },
  {
    id: 'dev-3',
    name: 'جهاز بصمة فرع جدة (Western Branch Gate)',
    ipAddress: '10.20.5.15',
    port: 4370,
    serialNumber: 'ZK-TF200-33418',
    protocol: 'cloud',
    location: 'فرع المنطقة الغربية - الاستقبال',
    status: 'online',
    lastSyncTime: '2026-09-03T08:35:00Z',
    totalRegisteredUsers: 35,
    apiKey: 'zk_west_cloud_33418',
    firmwareVersion: 'Ver 7.10 (Jan 2026)',
  },
];

// ----------------------------------------------------
// INITIAL BIOMETRIC ATTENDANCE RECORDS (TODAY & RECENT)
// ----------------------------------------------------
export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att-101',
    userId: 'emp-3',
    userName: 'ريم العتيبي',
    userNameEn: 'Reem Al-Otaibi',
    userEmail: 'reem.otaibi@dawamy.app',
    department: 'الموارد البشرية',
    departmentEn: 'Human Resources',
    biometricEnrollId: '103',
    date: '2026-09-03',
    checkInTime: '09:00:15',
    checkOutTime: '17:05:22',
    status: 'present',
    lateMinutes: 0,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 0,
    dailyShortageHours: 0,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'fingerprint',
    deviceId: 'dev-1',
    deviceName: 'جهاز البصمة - المدخل الرئيسي',
    deviceLocation: 'المبنى الرئيسي - بوابة 1',
    totalWorkingHours: 8.08,
    rawPunchLog: 'ENROLL:103|PUNCH:IN|DEV:dev-1|TIME:09:00:15|VERIFY:FP',
  },
  {
    id: 'att-102',
    userId: 'emp-6',
    userName: 'فيصل الغامدي',
    userNameEn: 'Faisal Al-Ghamdi',
    userEmail: 'faisal.ghamdi@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '106',
    date: '2026-09-03',
    checkInTime: '09:10:44',
    checkOutTime: '17:00:10',
    status: 'present',
    lateMinutes: 0,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 0,
    dailyShortageHours: 0,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'face',
    deviceId: 'dev-2',
    deviceName: 'جهاز بصمة الوجه - الدور الرابع',
    deviceLocation: 'برج الابتكار - الطابق 4',
    totalWorkingHours: 7.82,
    rawPunchLog: 'ENROLL:106|PUNCH:IN|DEV:dev-2|TIME:09:10:44|VERIFY:FACE',
  },
  {
    id: 'att-103',
    userId: 'emp-2',
    userName: 'طارق الخالدي',
    userNameEn: 'Tariq Al-Khalidi',
    userEmail: 'tariq.khalidi@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '102',
    date: '2026-09-03',
    checkInTime: '09:14:20',
    checkOutTime: '16:30:00',
    status: 'early_leave',
    lateMinutes: 0,
    earlyLeaveMinutes: 30,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 30,
    dailyShortageHours: 0.5,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'face',
    deviceId: 'dev-2',
    deviceName: 'جهاز بصمة الوجه - الدور الرابع',
    deviceLocation: 'برج الابتكار - الطابق 4',
    totalWorkingHours: 7.26,
    notes: 'انصراف مبكر 30 دقيقة قبل انتهاء الدوام الرسمي (05:00 م)',
    rawPunchLog: 'ENROLL:102|PUNCH:IN|DEV:dev-2|TIME:09:14:20|VERIFY:FACE',
  },
  {
    id: 'att-104',
    userId: 'emp-7',
    userName: 'ياسمين الحربي',
    userNameEn: 'Yasmin Al-Harbi',
    userEmail: 'yasmin.harbi@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '107',
    date: '2026-09-03',
    checkInTime: '09:35:12',
    checkOutTime: '17:00:00',
    status: 'late',
    lateMinutes: 35,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 35,
    dailyShortageHours: 0.58,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'fingerprint',
    deviceId: 'dev-1',
    deviceName: 'جهاز البصمة - المدخل الرئيسي',
    deviceLocation: 'المبنى الرئيسي - بوابة 1',
    totalWorkingHours: 7.41,
    notes: 'تأخر حضور 35 دقيقة عن موعد بدء الدوام الرسمي (09:00 ص)',
    rawPunchLog: 'ENROLL:107|PUNCH:IN|DEV:dev-1|TIME:09:35:12|VERIFY:FP',
  },
  {
    id: 'att-105',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userNameEn: 'Ahmed Al-Qahtani',
    userEmail: 'ahmed.qahtani@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '104',
    date: '2026-09-03',
    checkInTime: '09:30:05',
    checkOutTime: '16:45:00',
    status: 'late_and_early',
    lateMinutes: 30,
    earlyLeaveMinutes: 15,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 45,
    dailyShortageHours: 0.75,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'fingerprint',
    deviceId: 'dev-1',
    deviceName: 'جهاز البصمة - المدخل الرئيسي',
    deviceLocation: 'المبنى الرئيسي - بوابة 1',
    totalWorkingHours: 7.25,
    notes: 'تأخر حضور 30 دقيقة وانصراف مبكر 15 دقيقة (إجمالي العجز 45 دقيقة)',
    rawPunchLog: 'ENROLL:104|PUNCH:IN|DEV:dev-1|TIME:09:30:05|VERIFY:FP',
  },
  {
    id: 'att-106',
    userId: 'emp-1',
    userName: 'سارة المنصور',
    userNameEn: 'Sara Al-Mansoor',
    userEmail: 'sara.mansoor@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '101',
    date: '2026-09-03',
    checkInTime: '09:00:00',
    checkOutTime: '17:00:00',
    status: 'wfh',
    lateMinutes: 0,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 0,
    dailyShortageHours: 0,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'manual',
    deviceLocation: 'الرياض (حضور افتراضي - عمل عن بعد)',
    totalWorkingHours: 8.0,
    notes: 'تم تسجيل الحضور عبر منصة دوامي بنظام العمل الهجين المعتمد',
  },
  {
    id: 'att-107',
    userId: 'emp-5',
    userName: 'نورة الدوسري',
    userNameEn: 'Noura Al-Dossari',
    userEmail: 'noura.dossari@dawamy.app',
    department: 'المنتج والتصميم',
    departmentEn: 'Product & Design',
    biometricEnrollId: '105',
    date: '2026-09-03',
    checkInTime: '09:50:00',
    checkOutTime: '17:00:00',
    status: 'late',
    lateMinutes: 50,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 50,
    dailyShortageHours: 0.83,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'face',
    deviceId: 'dev-2',
    deviceName: 'جهاز بصمة الوجه - الدور الرابع',
    deviceLocation: 'برج الابتكار - الطابق 4',
    totalWorkingHours: 7.17,
    notes: 'تأخر 50 دقيقة عن موعد بدء الدوام الرسمي (09:00 ص)',
    rawPunchLog: 'ENROLL:105|PUNCH:IN|DEV:dev-2|TIME:09:50:00|VERIFY:FACE',
  },
  {
    id: 'att-108',
    userId: 'emp-5',
    userName: 'نورة الدوسري',
    userNameEn: 'Noura Al-Dossari',
    userEmail: 'noura.dossari@dawamy.app',
    department: 'المنتج والتصميم',
    departmentEn: 'Product & Design',
    biometricEnrollId: '105',
    date: '2026-09-01',
    checkInTime: '09:45:00',
    checkOutTime: '16:30:00',
    status: 'late_and_early',
    lateMinutes: 45,
    earlyLeaveMinutes: 30,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 75,
    dailyShortageHours: 1.25,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'face',
    deviceId: 'dev-2',
    deviceName: 'جهاز بصمة الوجه - الدور الرابع',
    deviceLocation: 'برج الابتكار - الطابق 4',
    totalWorkingHours: 6.75,
    notes: 'تأخر 45 دقيقة صباحاً وانصراف مبكر 30 دقيقة (عجز ساعة و15 دقيقة)',
    rawPunchLog: 'ENROLL:105|PUNCH:IN|DEV:dev-2|TIME:09:45:00|VERIFY:FACE',
  },
  {
    id: 'att-109',
    userId: 'emp-5',
    userName: 'نورة الدوسري',
    userNameEn: 'Noura Al-Dossari',
    userEmail: 'noura.dossari@dawamy.app',
    department: 'المنتج والتصميم',
    departmentEn: 'Product & Design',
    biometricEnrollId: '105',
    date: '2026-09-02',
    checkInTime: '10:15:00',
    checkOutTime: '17:15:00',
    status: 'late',
    lateMinutes: 75,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 75,
    dailyShortageHours: 1.25,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'face',
    deviceId: 'dev-2',
    deviceName: 'جهاز بصمة الوجه - الدور الرابع',
    deviceLocation: 'برج الابتكار - الطابق 4',
    totalWorkingHours: 7.0,
    notes: 'تأخر 75 دقيقة عن موعد الحضور الرسمي',
    rawPunchLog: 'ENROLL:105|PUNCH:IN|DEV:dev-2|TIME:10:15:00|VERIFY:FACE',
  },
  {
    id: 'att-110',
    userId: 'emp-5',
    userName: 'نورة الدوسري',
    userNameEn: 'Noura Al-Dossari',
    userEmail: 'noura.dossari@dawamy.app',
    department: 'المنتج والتصميم',
    departmentEn: 'Product & Design',
    biometricEnrollId: '105',
    date: '2026-09-04',
    checkInTime: '09:35:00',
    checkOutTime: '17:00:00',
    status: 'late',
    lateMinutes: 35,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 35,
    dailyShortageHours: 0.58,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'face',
    deviceId: 'dev-2',
    deviceName: 'جهاز بصمة الوجه - الدور الرابع',
    deviceLocation: 'برج الابتكار - الطابق 4',
    totalWorkingHours: 7.42,
    notes: 'تأخر 35 دقيقة عن موعد بدء الدوام الرسمي',
    rawPunchLog: 'ENROLL:105|PUNCH:IN|DEV:dev-2|TIME:09:35:00|VERIFY:FACE',
  },
  {
    id: 'att-111',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userNameEn: 'Ahmed Al-Qahtani',
    userEmail: 'ahmed.qahtani@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '104',
    date: '2026-09-02',
    checkInTime: '09:50:00',
    checkOutTime: '17:00:00',
    status: 'late',
    lateMinutes: 50,
    earlyLeaveMinutes: 0,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 50,
    dailyShortageHours: 0.83,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'fingerprint',
    deviceId: 'dev-1',
    deviceName: 'جهاز البصمة - المدخل الرئيسي',
    deviceLocation: 'المبنى الرئيسي - بوابة 1',
    totalWorkingHours: 7.17,
    notes: 'تأخر 50 دقيقة صباحية (تم استهلاكها من رصيد الـ 4 ساعات الممنوحة)',
  },
  {
    id: 'att-112',
    userId: 'emp-1',
    userName: 'سارة المنصور',
    userNameEn: 'Sara Al-Mansoor',
    userEmail: 'sara.mansoor@dawamy.app',
    department: 'الهندسة والتطوير',
    departmentEn: 'Engineering',
    biometricEnrollId: '101',
    date: '2026-09-02',
    checkInTime: '09:00:00',
    checkOutTime: '16:15:00',
    status: 'early_leave',
    lateMinutes: 0,
    earlyLeaveMinutes: 45,
    dailyRequiredHours: 8.0,
    dailyShortageMinutes: 45,
    dailyShortageHours: 0.75,
    officialStartTime: '09:00',
    officialEndTime: '17:00',
    verifyMethod: 'manual',
    deviceLocation: 'الرياض (حضور افتراضي)',
    totalWorkingHours: 7.25,
    notes: 'انصراف مبكر 45 دقيقة بإذن رسمي',
  },
];

export const INITIAL_DEDUCTIONS: SalaryDeduction[] = [
  {
    id: 'ded-101',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userNameEn: 'Ahmed Al-Qahtani',
    userEmail: 'ahmed.qahtani@dawamy.app',
    department: 'الهندسة والتطوير',
    month: '2026-09',
    type: 'penalty_disciplinary',
    title: 'خصم جزاء إداري - تأخر تسليم متطلب التدقيق الأمني',
    titleEn: 'Disciplinary Penalty - Security Audit Delay',
    amount: 483.33,
    daysDeducted: 1,
    date: '2026-09-02',
    status: 'applied',
    reason: 'مخالفة لائحة الالتزام الداخلي للمشاريع الحرجة وتأخر التسليم بدون إخطار مسبق',
    issuedBy: 'إدارة الموارد البشرية والامتثال',
    issuedAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 'ded-102',
    userId: 'emp-6',
    userName: 'فيصل الغامدي',
    userNameEn: 'Faisal Al-Ghamdi',
    userEmail: 'faisal.ghamdi@dawamy.app',
    department: 'الهندسة والتطوير',
    month: '2026-09',
    type: 'unexcused_absence',
    title: 'خصم يوم لعدم تسجيل الحضور في المنظومة',
    titleEn: 'Unregistered Attendance Penalty',
    amount: 506.67,
    daysDeducted: 1,
    date: '2026-09-01',
    status: 'waived',
    reason: 'عدم وجود بصمة حضور في المنصة صباح يوم الثلاثاء',
    issuedBy: 'الموارد البشرية (ريم العتيبي)',
    issuedAt: '2026-09-01T17:00:00Z',
    waivedAt: '2026-09-02T09:30:00Z',
    waivedBy: 'ريم العتيبي (أخصائية الموارد البشرية)',
    waivedReason: 'تم تقديم إفادة رسمية بمهمة عمل ميدانية عاجلة لتركيب خوادم بالدور الأرضي',
  },
];

export const INITIAL_SALARY_ADVANCES: SalaryAdvance[] = [
  {
    id: 'adv-101',
    advanceNumber: 'ADV-2026-001',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userNameEn: 'Ahmed Al-Qahtani',
    userEmail: 'ahmed.qahtani@dawamy.app',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    requestDate: '2026-07-25',
    totalAmount: 6000,
    installmentsCount: 6,
    monthlyInstallmentAmount: 1000,
    startMonth: '2026-08',
    endMonth: '2027-01',
    reason: 'سلفة طارئة لتغطية رسوم تسجيل دراسي عائلي',
    status: 'approved',
    approvedBy: 'ريم العتيبي (الموارد البشرية)',
    approvedAt: '2026-07-26T10:00:00Z',
    paidAmount: 1000,
    remainingAmount: 5000,
    paidInstallmentsCount: 1,
    employeeSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="280" height="90" viewBox="0 0 280 90"><path d="M 25 55 Q 60 15, 85 50 T 140 45 T 195 40 Q 220 75, 245 25" fill="none" stroke="%231E3A8A" stroke-width="3" stroke-linecap="round"/><path d="M 45 72 Q 130 65, 215 74" fill="none" stroke="%231E3A8A" stroke-width="2" stroke-linecap="round"/></svg>',
    approverSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="280" height="90" viewBox="0 0 280 90"><path d="M 30 50 Q 75 10, 110 45 T 170 40 Q 220 20, 240 60" fill="none" stroke="%2318181B" stroke-width="3" stroke-linecap="round"/><path d="M 40 70 Q 140 60, 230 72" fill="none" stroke="%2318181B" stroke-width="2" stroke-linecap="round"/></svg>',
    installments: [
      { id: 'inst-1', installmentNumber: 1, month: '2026-08', amount: 1000, status: 'deducted', deductedAt: '2026-08-31' },
      { id: 'inst-2', installmentNumber: 2, month: '2026-09', amount: 1000, status: 'pending' },
      { id: 'inst-3', installmentNumber: 3, month: '2026-10', amount: 1000, status: 'pending' },
      { id: 'inst-4', installmentNumber: 4, month: '2026-11', amount: 1000, status: 'pending' },
      { id: 'inst-5', installmentNumber: 5, month: '2026-12', amount: 1000, status: 'pending' },
      { id: 'inst-6', installmentNumber: 6, month: '2027-01', amount: 1000, status: 'pending' },
    ],
    createdAt: '2026-07-25T14:30:00Z',
  },
  {
    id: 'adv-102',
    advanceNumber: 'ADV-2026-002',
    userId: 'emp-6',
    userName: 'فيصل الغامدي',
    userNameEn: 'Faisal Al-Ghamdi',
    userEmail: 'faisal.ghamdi@dawamy.app',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    requestDate: '2026-08-20',
    totalAmount: 9000,
    installmentsCount: 3,
    monthlyInstallmentAmount: 3000,
    startMonth: '2026-09',
    endMonth: '2026-11',
    reason: 'سلفة صيانة وترميم مسكن عائلي',
    status: 'approved',
    approvedBy: 'طارق الخالدي (مدير الفريق)',
    approvedAt: '2026-08-21T09:15:00Z',
    paidAmount: 0,
    remainingAmount: 9000,
    paidInstallmentsCount: 0,
    employeeSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="280" height="90" viewBox="0 0 280 90"><path d="M 20 40 Q 70 8, 100 50 T 160 35 Q 210 65, 250 30" fill="none" stroke="%235E7153" stroke-width="3.2" stroke-linecap="round"/><path d="M 35 75 Q 120 62, 230 70" fill="none" stroke="%235E7153" stroke-width="2" stroke-linecap="round"/></svg>',
    approverSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="280" height="90" viewBox="0 0 280 90"><path d="M 20 40 Q 70 8, 100 50 T 160 35 Q 210 65, 250 30" fill="none" stroke="%235E7153" stroke-width="3.2" stroke-linecap="round"/><path d="M 35 75 Q 120 62, 230 70" fill="none" stroke="%235E7153" stroke-width="2" stroke-linecap="round"/></svg>',
    installments: [
      { id: 'inst-201', installmentNumber: 1, month: '2026-09', amount: 3000, status: 'pending' },
      { id: 'inst-202', installmentNumber: 2, month: '2026-10', amount: 3000, status: 'pending' },
      { id: 'inst-203', installmentNumber: 3, month: '2026-11', amount: 3000, status: 'pending' },
    ],
    createdAt: '2026-08-20T11:00:00Z',
  },
];

