import { UserProfile, LeaveOrWfhRequest, TeamMemberStatus, NotificationItem, PolicyFaqItem } from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'emp-1',
    name: 'سارة المنصور',
    nameEn: 'Sara Al-Mansoor',
    email: 'sara.mansoor@dawamy.app',
    role: 'employee',
    title: 'مهندسة برمجيات أولى (Senior Software Engineer)',
    titleEn: 'Senior Software Engineer',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    managerName: 'م. طارق الخالدي',
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 3,
      annualLeaveTotal: 25,
      annualLeaveUsed: 6,
      sickLeaveUsed: 1,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'wfh_active',
    checkInTime: '08:45 AM',
    currentTasks: [
      'تطوير نظام الاعتمادات الفورية وتحديث API الخادم',
      'مراجعة كود البنية التحتية لحاويات Cloud Run',
      'اجتماع المواءمة التقنية وتنسيق المهام',
    ],
    dailyTasks: [
      {
        id: 'task-101',
        title: 'تطوير نظام الاعتمادات الفورية وتحديث API الخادم',
        dueTime: '11:30 AM',
        completed: true,
        priority: 'high',
        category: 'برمجة وتطوير',
        notes: 'تم فحص الـ Endpoints وتكامل Firestore بنجاح',
        completedAt: '10:45 AM',
      },
      {
        id: 'task-102',
        title: 'مراجعة كود البنية التحتية لحاويات Cloud Run والمنفذ 3000',
        dueTime: '02:00 PM',
        completed: false,
        priority: 'high',
        category: 'بنية تحتية',
        notes: 'التحقق من إعدادات Nginx والتأكد من استقرار المزامنة',
      },
      {
        id: 'task-103',
        title: 'اجتماع المواءمة التقنية ومزامنة الفريق الصباحي',
        dueTime: '03:30 PM',
        completed: false,
        priority: 'medium',
        category: 'اجتماعات',
        notes: 'استعراض مخرجات العمل عن بُعد مع المهندس طارق',
      },
      {
        id: 'task-104',
        title: 'إرسال تقرير الإنجاز اليومي (Daily Standup Recap) في سلاك',
        dueTime: '05:00 PM',
        completed: false,
        priority: 'normal',
        category: 'تقارير ومتابعة',
        notes: 'مشاركة ملخص المهام المنجزة قبل نهاية الدوام',
      },
    ],
  },
  {
    id: 'emp-2',
    name: 'طارق الخالدي',
    nameEn: 'Tariq Al-Khalidi',
    email: 'tariq.khalidi@dawamy.app',
    role: 'manager',
    title: 'مدير الفريق الهندسي (Engineering Lead)',
    titleEn: 'Engineering Lead',
    department: 'الهندسة والتطوير (Engineering)',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    managerName: 'د. خالد الزهراني',
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 2,
      annualLeaveTotal: 25,
      annualLeaveUsed: 4,
      sickLeaveUsed: 0,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'in_office',
    checkInTime: '08:15 AM',
    currentTasks: [
      'اجتماع مواءمة الربع السنوي مع الإدارة',
      'اعتماد طلبات الإجازات والعمل عن بعد للفريق',
      'مراجعة تقييم أداء مهندسي الفريق',
    ],
    dailyTasks: [
      {
        id: 'task-201',
        title: 'مراجعة واعتماد طلبات الإجازات والعمل عن بعد في المنصة',
        dueTime: '10:30 AM',
        completed: true,
        priority: 'high',
        category: 'اعتمادات وإشراف',
        completedAt: '09:50 AM',
      },
      {
        id: 'task-202',
        title: 'اجتماع مواءمة الربع السنوي مع الإدارة العامة',
        dueTime: '01:00 PM',
        completed: false,
        priority: 'high',
        category: 'اجتماعات',
      },
      {
        id: 'task-203',
        title: 'مراجعة الخطة التشغيلية لمهندسي البرمجيات لشهر سبتمبر',
        dueTime: '04:30 PM',
        completed: false,
        priority: 'medium',
        category: 'تخطيط واستراتيجية',
      },
    ],
  },
  {
    id: 'emp-3',
    name: 'ريم العتيبي',
    nameEn: 'Reem Al-Otaibi',
    email: 'reem.otaibi@dawamy.app',
    role: 'hr',
    title: 'أخصائية الموارد البشرية والامتثال (HR & People Specialist)',
    titleEn: 'HR & People Specialist',
    department: 'الموارد البشرية (People & HR)',
    departmentEn: 'Human Resources',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    managerName: 'أ. عبد الله السالم',
    balances: {
      wfhMonthlyTotal: 8,
      wfhMonthlyUsed: 1,
      annualLeaveTotal: 25,
      annualLeaveUsed: 2,
      sickLeaveUsed: 0,
      emergencyLeaveUsed: 0,
    },
    todayStatus: 'in_office',
    checkInTime: '08:00 AM',
    currentTasks: [
      'تدقيق سجلات الحضور وساعات الدوام المرن',
      'تحديث سياسات العمل الهجين والامتثال للائحة',
      'مراجعة خطط الإنابة وتغطية الإجازات السنوية',
    ],
    dailyTasks: [
      {
        id: 'task-301',
        title: 'تدقيق سجلات الحضور الافتراضي وساعات الدوام المرن',
        dueTime: '11:00 AM',
        completed: true,
        priority: 'high',
        category: 'موارد بشرية وامتثال',
        completedAt: '10:15 AM',
      },
      {
        id: 'task-302',
        title: 'تحديث دليل سياسات العمل الهجين ولائحة نظام العمل',
        dueTime: '02:30 PM',
        completed: false,
        priority: 'medium',
        category: 'سياسات ولوائح',
      },
      {
        id: 'task-303',
        title: 'مراجعة وتأكيد خطط الإنابة للموظفين المسافرين هذا الأسبوع',
        dueTime: '04:00 PM',
        completed: false,
        priority: 'normal',
        category: 'متابعة وإشراف',
      },
    ],
  },
];

export const INITIAL_REQUESTS: LeaveOrWfhRequest[] = [
  {
    id: 'REQ-1092',
    userId: 'emp-1',
    userName: 'سارة المنصور',
    userTitle: 'مهندسة برمجيات أولى',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    type: 'remote',
    startDate: '2026-09-03',
    endDate: '2026-09-03',
    totalDays: 1,
    reason: 'التركيز المكثف على إنهاء اختبارات الأداء وسد الثغرات الأمنية قبل إطلاق الإصدار القادم.',
    isAiGeneratedReason: true,
    handoverColleague: 'أحمد القحطاني',
    handoverPlan: 'متابعة التنبيهات العاجلة على سيرفر الإنتاج في حال دعت الحاجة.',
    status: 'approved',
    createdAt: '2026-09-01T10:30:00Z',
    managerNotes: 'معتمد مع تمنياتي بالتوفيق في إنجاز الاختبارات.',
    approvedByManagerAt: '2026-09-01T11:00:00Z',
  },
  {
    id: 'REQ-1093',
    userId: 'emp-4',
    userName: 'أحمد القحطاني',
    userTitle: 'مطور واجهات أمامية (Frontend Engineer)',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    type: 'annual_leave',
    startDate: '2026-09-10',
    endDate: '2026-09-14',
    totalDays: 3,
    reason: 'إجازة سنوية مجدولة للراحة وتجديد الطاقة بعد انتهاء مرحلة التصميم الرئيسية.',
    isAiGeneratedReason: true,
    handoverColleague: 'سارة المنصور',
    handoverPlan: 'تم تسليم كافة ملفات Figma ومكونات React لسارة لتغطية أي تعديلات طارئة.',
    status: 'pending_manager',
    createdAt: '2026-09-02T08:15:00Z',
  },
  {
    id: 'REQ-1094',
    userId: 'emp-5',
    userName: 'نورة الدوسري',
    userTitle: 'مصممة تجربة المستخدم (UI/UX Designer)',
    department: 'التصميم والابتكار',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    type: 'remote',
    startDate: '2026-09-04',
    endDate: '2026-09-04',
    totalDays: 1,
    reason: 'إجراء مقابلات بحثية مع المستخدمين واختبار النماذج الأولية في بيئة هادئة.',
    isAiGeneratedReason: true,
    handoverColleague: 'سارة المنصور',
    status: 'pending_manager',
    createdAt: '2026-09-02T09:40:00Z',
  },
  {
    id: 'REQ-1090',
    userId: 'emp-6',
    userName: 'فيصل الغامدي',
    userTitle: 'أخصائي قواعد بيانات (DevOps & DBA)',
    department: 'الهندسة والتطوير',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    type: 'sick_leave',
    startDate: '2026-08-28',
    endDate: '2026-08-28',
    totalDays: 1,
    reason: 'مراجعة عيادة الأسنان وإجراء جراحة صغرى.',
    status: 'approved',
    createdAt: '2026-08-28T07:10:00Z',
    approvedByManagerAt: '2026-08-28T07:45:00Z',
    approvedByHrAt: '2026-08-28T08:30:00Z',
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMemberStatus[] = [
  {
    id: 'emp-1',
    name: 'سارة المنصور',
    nameEn: 'Sara Al-Mansoor',
    role: 'مهندسة برمجيات أولى',
    roleEn: 'Senior Software Engineer',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'wfh_active',
    location: 'الرياض (عن بُعد)',
    locationEn: 'Riyadh (Remote)',
    checkInTime: '08:45 AM',
    currentFocus: 'تطوير وحدة الدوام المرن والذكاء الاصطناعي',
    currentFocusEn: 'Developing smart hybrid workflow & Gemini AI logic',
  },
  {
    id: 'emp-2',
    name: 'طارق الخالدي',
    nameEn: 'Tariq Al-Khalidi',
    role: 'مدير الفريق الهندسي',
    roleEn: 'Engineering Lead',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'in_office',
    location: 'المكتب الرئيسي - الدور 4',
    locationEn: 'HQ - 4th Floor',
    checkInTime: '08:15 AM',
    currentFocus: 'مراجعات التصميم واعتماد الطلبات',
    currentFocusEn: 'Design review & approving pending team requests',
  },
  {
    id: 'emp-4',
    name: 'أحمد القحطاني',
    nameEn: 'Ahmed Al-Qahtani',
    role: 'مطور واجهات أمامية',
    roleEn: 'Frontend Engineer',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'in_office',
    location: 'المكتب الرئيسي - الدور 4',
    locationEn: 'HQ - 4th Floor',
    checkInTime: '08:30 AM',
    currentFocus: 'تحسين تجربة الجوال وتأثيرات الواجهة',
    currentFocusEn: 'Improving mobile responsiveness & UI micro-interactions',
  },
  {
    id: 'emp-5',
    name: 'نورة الدوسري',
    nameEn: 'Noura Al-Dossari',
    role: 'مصممة تجربة المستخدم',
    roleEn: 'UI/UX Designer',
    department: 'التصميم',
    departmentEn: 'Design & Innovation',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'deep_focus',
    location: 'المكتب الرئيسي - منطقة الهدوء',
    locationEn: 'HQ - Quiet Zone',
    checkInTime: '09:00 AM',
    currentFocus: 'تصميم نموذج تقويم الإجازات التفاعلي',
    currentFocusEn: 'Designing the interactive presence calendar mockup',
  },
  {
    id: 'emp-6',
    name: 'فيصل الغامدي',
    nameEn: 'Faisal Al-Ghamdi',
    role: 'مهندس DevOps وسيرفرات',
    roleEn: 'DevOps & DBA Specialist',
    department: 'الهندسة',
    departmentEn: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    status: 'in_office',
    location: 'المكتب الرئيسي - الدور 4',
    locationEn: 'HQ - 4th Floor',
    checkInTime: '08:10 AM',
    currentFocus: 'ضبط إعدادات Cloud Run ومراقبة المنفذ 3000',
    currentFocusEn: 'Monitoring Cloud Run container & port 3000 health',
  },
  {
    id: 'emp-7',
    name: 'ياسمين الحربي',
    nameEn: 'Yasmin Al-Harbi',
    role: 'محللة نظم وضمان الجودة',
    roleEn: 'QA & Systems Analyst',
    department: 'الجودة والأنظمة',
    departmentEn: 'QA & Quality Assurance',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'in_meeting',
    location: 'قاعة الاجتماعات 2B',
    locationEn: 'Meeting Room 2B',
    checkInTime: '08:50 AM',
    currentFocus: 'اختبار قبول المستخدم (UAT)',
    currentFocusEn: 'User Acceptance Testing (UAT)',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'تم اعتماد طلب العمل عن بعد ✅',
    titleEn: 'Remote Work Request Approved ✅',
    message: 'وافق المدير م. طارق الخالدي على طلبك للعمل عن بعد ليوم الخميس 3 سبتمبر.',
    messageEn: 'Engineering Lead Tariq Al-Khalidi approved your WFH request for Thu, Sep 3.',
    type: 'approval',
    timestamp: 'منذ 25 دقيقة',
    read: false,
    requestId: 'REQ-1092',
  },
  {
    id: 'notif-2',
    title: 'تذكير: تسجيل الحضور الافتراضي ⏰',
    titleEn: 'Virtual Check-In Logged ⏰',
    message: 'تم تسجيل حضورك الافتراضي بنجاح اليوم عند الساعة 08:45 ص.',
    messageEn: 'Your attendance check-in was successfully logged today at 08:45 AM.',
    type: 'system',
    timestamp: 'اليوم، 08:45 ص',
    read: true,
  },
  {
    id: 'notif-3',
    title: 'تحديث سياسة الدوام المرن 📢',
    titleEn: 'Hybrid Policy Update 📢',
    message: 'تم تحديث سياسة العمل الهجين مع إتاحة خيار العمل لنصف يوم مرن.',
    messageEn: 'Updated hybrid working guidelines with flexible half-day options.',
    type: 'reminder',
    timestamp: 'أمس، 02:00 م',
    read: true,
  },
];

export const POLICY_FAQS: PolicyFaqItem[] = [
  {
    questionAr: 'كم عدد أيام العمل عن بُعد المسموحة شهرياً؟',
    questionEn: 'How many WFH days are allowed per month?',
    summaryAr: 'يحق للموظف يومين في الأسبوع (بحد أقصى 8 أيام شهرياً) بموافقة المدير المباشر وتنسيق التغطية.',
    summaryEn: 'Up to 2 days per week (max 8 per month) with direct manager approval.',
    tag: 'العمل عن بعد (WFH)',
  },
  {
    questionAr: 'ما هي ساعات التواجد الأساسية (Core Hours) خلال العمل عن بعد؟',
    questionEn: 'What are the mandatory core hours during WFH?',
    summaryAr: 'ساعات التواجد الإلزامية عبر سلاك والبريد هي من 10:00 صباحاً وحتى 04:00 مساءً.',
    summaryEn: 'Core availability hours are 10:00 AM to 4:00 PM on Slack, Teams and email.',
    tag: 'ساعات الدوام',
  },
  {
    questionAr: 'ما هي المهلة الزمنية لتقديم طلب الإجازة السنوية؟',
    questionEn: 'What is the notice period for annual leave requests?',
    summaryAr: 'يجب تقديم طلب الإجازة السنوية قبل 48 ساعة على الأقل للإجازات القصيرة (1-3 أيام)، وقبل أسبوع للإجازات الأطول.',
    summaryEn: 'Submit at least 48 hours in advance for 1-3 days, and 1 week for longer leaves.',
    tag: 'الإجازات السنوية',
  },
  {
    questionAr: 'كيف يتم اعتماد الإجازة المرضية وتوثيقها؟',
    questionEn: 'How is sick leave verified and documented?',
    summaryAr: 'يجب رفع التقرير الطبي المعتمد من منصة صحتي أو المستشفى عبر المنصة خلال 24 ساعة من تاريخ الغياب.',
    summaryEn: 'Upload certified medical certificate via Sehaty/clinic within 24 hours.',
    tag: 'الإجازات المرضية',
  },
];
